# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.warning.mode=all

# Window Stuff
window_height=900
window_width=1600

# MC stuff
minecraft_version=1.21.1

# Mod stuff
mod_archives_name=Fae's Cobblemizer Redux
mod_authors=Fayvira-DraGon
mod_contact=https://linktr.ee/FayviraDraGon
mod_description=Adds items that allow players to manipulate various stats and aesthetic characteristics of Pokémon within the game.
mod_github=https://github.com/Fayvira-DraGon/FaesCobblemizer
mod_group=github.fayvira.fabric
mod_homepage=https://modrinth.com/mod/faes-cobblemizer
mod_id=cobblemizer
mod_license=MIT
mod_name=FaesCobblemizerRedux
mod_version=3.0.9-1.21.1

# Loaders
devauth_version=1.2.1
fabric_api_version=0.116.12+1.21.1
fabric_command_api_version=fabric-command-api-v2
fabric_loader_version=0.19.2
java_version=21
junit-jupiter-api_version=5.10.0
junit-jupiter-engine_version=5.10.0
kotlin_version=1.13.11+kotlin.2.3.21
yarn_mappings=1.21.1+build.3

# Other deps
cobblemon_version=1.7.3+1.21.1
owo_version=0.12.15.4+1.21
kotlin_stdlib=jdk8